from dataclasses import dataclass
from pathlib import Path
import re


@dataclass(frozen=True, slots=True)
class InitializedWorkspace:
    workspace_root: Path
    monitor_id: str


def initialize_workspace(*, workspace_root: Path) -> InitializedWorkspace:
    resolved_root = workspace_root.resolve()
    if resolved_root.exists():
        if not resolved_root.is_dir():
            raise ValueError(f"Workspace path is not a directory: {resolved_root}")
        if any(resolved_root.iterdir()):
            raise ValueError(f"Workspace path must be empty before initialization: {resolved_root}")
    else:
        resolved_root.mkdir(parents=True, exist_ok=True)

    monitor_id = _build_monitor_id(resolved_root.name)
    _write_file(
        resolved_root / "services.yml",
        """
services:
  local_model:
    plugin: noop_model
  local_output:
    plugin: file_notifier
    path: output/digest.txt
""".lstrip(),
    )
    _write_file(
        resolved_root / "analysis_profiles.yml",
        """
analysis_profiles:
  digest_v1:
    plugin: builtin_summary
    model_service: local_model
""".lstrip(),
    )
    _write_file(
        resolved_root / "monitors.yml",
        f"""
monitors:
  - id: {monitor_id}
    schedule: "*/5 * * * *"
    source:
      plugin: builtin_json_file
      config:
        path: input/feed.json
    analyses:
      - profile: digest_v1
    outputs:
      - profile: digest_v1
        renderer: builtin_digest
        service: local_output
""".lstrip(),
    )
    _write_file(
        resolved_root / "input" / "feed.json",
        """[
  {
    "source_id": "meeting-2026-03-14",
    "content": "Agenda published for the community meeting."
  },
  {
    "source_id": "memo-2026-03-15",
    "content": "Budget note updated with two action items."
  }
]
""",
    )
    _write_file(
        resolved_root / "README.md",
        f"""# {resolved_root.name}

This workspace was generated by `python -m observer_rock init-workspace`.

## Operator Flow

Validate the workspace:

```powershell
python -m observer_rock validate-workspace --workspace .
```

List configured monitors:

```powershell
python -m observer_rock list-monitors --workspace .
```

Run the starter monitor:

```powershell
python -m observer_rock run-monitor {monitor_id} --workspace .
```

Run the scheduler for an explicit tick:

```powershell
python -m observer_rock run-scheduler --workspace . --tick 2026-03-14T12:05:00+00:00
```

## Files

- `services.yml`: local model and file output service
- `analysis_profiles.yml`: one digest profile
- `monitors.yml`: one monitor wired to the local feed
- `input/feed.json`: starter source records
- `output/digest.txt`: rendered digest written after the first run
- `.observer_rock/`: runtime state, persisted documents, and artifacts
""",
    )
    return InitializedWorkspace(workspace_root=resolved_root, monitor_id=monitor_id)


def _build_monitor_id(workspace_name: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", workspace_name.lower()).strip("-")
    if not normalized:
        normalized = "workspace"
    return f"{normalized}-digest"


def _write_file(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")
